require_relative "entities/coordinate"
require_relative "enums/direction"
require_relative "entities/boundary_coordinates"
require_relative "entities/robot"
require_relative "entities/table"
require_relative "controllers/command_controller"
require_relative "errors/command_error"
require_relative "errors/out_of_boundary_error"
